# Google Analytics
google_analytics_tracking_id: UA-40830548-1

url: http://exitiumonline.com
title: Exitium
author: Evan Lowry

root: /
permalink: /thoughts/:categories/:title
markdown: kramdown
highlighter: "rouge"

paginate: 10          # Posts per page on the blog index
paginate_path: "blog/page:num"
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

# Sharing Options
twitter_id: lykathia
