source: .
destination: ./_site
safe: false
auto: false

# Google Analytics
google_analytics_tracking_id:

# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://exitiumonline.com
title: Exitium - ...
author: Evan Lowry

root: /
permalink: /blog/:year/:month/:day/:title/
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
